---
- name: Add group "kubecicd"
  group:
    name: kubecicd
  become: yes

- name: Add user "kubecicd"
  user:
    name: kubecicd
    group: kubecicd
    home: /home/kubecicd
  become: yes

- name: Download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kubectl
    dest: /tmp/kubectl

